<?php

/**
 * @file
 * Hooks and main functions for Rooms Package module.
 */

/**
 * Implements hook_commerce_product_type_info().
 */
function rooms_package_commerce_product_type_info() {
  return array(
    'rooms_package' => array(
      'type' => 'rooms_package',
      'name' => t('Rooms Packages'),
      'description' => t('Provides support for creating package solutions for Rooms.'),
      'revision' => '1',
    ),
  );
}
